// <auto-generated />
using System;
using System.Collections.Generic;
using BookStore.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookStore.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240912024137_SeedDataForBooks")]
    partial class SeedDataForBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("books")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Domain.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.ToTable("books", "books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09dbf58d-6571-4ab8-8742-bcd5e5b640e8"),
                            Author = "Ada Wolff",
                            Description = "Autem sunt ut porro ullam velit magni provident deleniti enim.",
                            Price = 167357.02072762350000m,
                            Quantity = 10,
                            Title = "Willms - Dickinson"
                        },
                        new
                        {
                            Id = new Guid("56600a9f-ae1f-4a28-b538-6b723f826e8e"),
                            Author = "Ada Wolff",
                            Description = "Quod ea reprehenderit porro id et reiciendis esse vel aut.",
                            Price = 189916.233294139790000m,
                            Quantity = 41,
                            Title = "Spinka, Hermann and Nolan"
                        },
                        new
                        {
                            Id = new Guid("c9052ba3-ea24-489a-948e-36a6f7107d61"),
                            Author = "Ada Wolff",
                            Description = "Eum omnis debitis iusto veniam sit.",
                            Price = 298910.40159248050000m,
                            Quantity = 17,
                            Title = "Becker, Paucek and Luettgen"
                        },
                        new
                        {
                            Id = new Guid("87c5fb04-4ca9-4dcd-93c5-a4e930a99216"),
                            Author = "Ada Wolff",
                            Description = "Nulla commodi ut et dolorem aut.",
                            Price = 71356.176777882490000m,
                            Quantity = 25,
                            Title = "Kilback, Lubowitz and Moen"
                        },
                        new
                        {
                            Id = new Guid("ff51cd0a-b3da-4584-97b9-aeca330f3eec"),
                            Author = "Ada Wolff",
                            Description = "Porro voluptatem nulla nam aliquid eaque doloribus.",
                            Price = 47448.0453999179290000m,
                            Quantity = 39,
                            Title = "Hamill, Wisozk and DuBuque"
                        },
                        new
                        {
                            Id = new Guid("c5126b75-790c-4f9d-89de-c624d1f58bdb"),
                            Author = "Ada Wolff",
                            Description = "Et quas et.",
                            Price = 167673.597666825240000m,
                            Quantity = 17,
                            Title = "Durgan - Stokes"
                        },
                        new
                        {
                            Id = new Guid("45ee62df-729e-436d-af10-a5a6307fdb11"),
                            Author = "Ada Wolff",
                            Description = "Dicta et quisquam exercitationem quae dolor voluptatem est illum.",
                            Price = 220409.570898782640000m,
                            Quantity = 43,
                            Title = "Weber - Lueilwitz"
                        },
                        new
                        {
                            Id = new Guid("5e3af6cd-d423-4996-bc44-1e98bd22493e"),
                            Author = "Ada Wolff",
                            Description = "Temporibus quasi est laborum sint praesentium cum aut ullam.",
                            Price = 487041.709256442330000m,
                            Quantity = 6,
                            Title = "Kunze Group"
                        },
                        new
                        {
                            Id = new Guid("12f460ff-6108-44ea-a07f-76154f1cafcb"),
                            Author = "Ada Wolff",
                            Description = "Aut itaque temporibus error distinctio.",
                            Price = 191176.727425578920000m,
                            Quantity = 88,
                            Title = "Leffler, Lubowitz and Gutkowski"
                        },
                        new
                        {
                            Id = new Guid("85446420-71da-487b-8dd5-2dd6dc9bd424"),
                            Author = "Ada Wolff",
                            Description = "Et facere nam et eligendi est consequatur pariatur ex.",
                            Price = 448824.934827247710000m,
                            Quantity = 4,
                            Title = "Emard LLC"
                        },
                        new
                        {
                            Id = new Guid("402498e7-1261-4038-b93f-fe6e988066a0"),
                            Author = "Ada Wolff",
                            Description = "Iste velit qui corrupti et assumenda dolore reiciendis eligendi consequatur.",
                            Price = 378463.794009723440000m,
                            Quantity = 57,
                            Title = "Reichert - Anderson"
                        },
                        new
                        {
                            Id = new Guid("5f6c5620-9b88-444e-9828-e69a08e49f95"),
                            Author = "Ada Wolff",
                            Description = "Sunt et autem aut.",
                            Price = 147827.33430711840000m,
                            Quantity = 89,
                            Title = "Lindgren - Ledner"
                        },
                        new
                        {
                            Id = new Guid("62df0e3d-0faf-4f02-a9c1-09194e932e8b"),
                            Author = "Ada Wolff",
                            Description = "Velit impedit ducimus fuga ipsum voluptas et sunt provident.",
                            Price = 496713.944360007840000m,
                            Quantity = 11,
                            Title = "Larkin - Ondricka"
                        },
                        new
                        {
                            Id = new Guid("b2c29a0f-742b-48fc-8138-5b1861831722"),
                            Author = "Ada Wolff",
                            Description = "Eum ducimus debitis est non placeat.",
                            Price = 155512.68845478610000m,
                            Quantity = 27,
                            Title = "Yundt - Wolf"
                        },
                        new
                        {
                            Id = new Guid("8df9d56a-1e41-4c17-a4ea-b72ce761c4d0"),
                            Author = "Ada Wolff",
                            Description = "Repellat accusamus sunt ducimus quam sed voluptatem.",
                            Price = 129923.246928640680000m,
                            Quantity = 57,
                            Title = "Daugherty, Sanford and Boehm"
                        },
                        new
                        {
                            Id = new Guid("9a67d25f-f9e6-4e34-a801-797f5175b164"),
                            Author = "Ada Wolff",
                            Description = "Debitis ut quos beatae officia modi omnis.",
                            Price = 358250.494325776980000m,
                            Quantity = 75,
                            Title = "Botsford LLC"
                        },
                        new
                        {
                            Id = new Guid("b466825c-0ce3-403a-95eb-6f55870b86ae"),
                            Author = "Ada Wolff",
                            Description = "Itaque tempore similique ipsam magni dolorum deserunt repellat.",
                            Price = 227285.59016431820000m,
                            Quantity = 78,
                            Title = "Greenholt - Jenkins"
                        },
                        new
                        {
                            Id = new Guid("ff67fe61-2459-4485-ae2f-c4442292333f"),
                            Author = "Ada Wolff",
                            Description = "Quia sapiente incidunt pariatur voluptatem.",
                            Price = 367884.984912897470000m,
                            Quantity = 45,
                            Title = "Lockman Group"
                        },
                        new
                        {
                            Id = new Guid("e5a7bec4-7dda-47f1-80bc-9cbc467dbbb2"),
                            Author = "Ada Wolff",
                            Description = "Rerum ut rerum autem dolore eum ut sed.",
                            Price = 20588.2311066940450000m,
                            Quantity = 56,
                            Title = "Kris, Mueller and D'Amore"
                        },
                        new
                        {
                            Id = new Guid("708d0815-de1b-41be-a787-d3753813e71b"),
                            Author = "Ada Wolff",
                            Description = "Nihil minus qui et eos consequuntur.",
                            Price = 261350.816021690420000m,
                            Quantity = 90,
                            Title = "Dibbert, Ruecker and Glover"
                        },
                        new
                        {
                            Id = new Guid("09045c0b-7e66-4c8a-a34c-f22b00d35fb3"),
                            Author = "Ada Wolff",
                            Description = "Sequi fugit neque eligendi quaerat ea impedit numquam.",
                            Price = 165849.845284121940000m,
                            Quantity = 96,
                            Title = "Hettinger and Sons"
                        },
                        new
                        {
                            Id = new Guid("f13fe049-e013-44ae-a8fd-6c3cc5abd0a1"),
                            Author = "Ada Wolff",
                            Description = "Voluptas consequatur iste voluptas est ipsum ut aut deleniti et.",
                            Price = 449255.564420609510000m,
                            Quantity = 67,
                            Title = "Gusikowski, Zulauf and Monahan"
                        },
                        new
                        {
                            Id = new Guid("7ad860be-2f30-4296-90eb-210ec204256e"),
                            Author = "Ada Wolff",
                            Description = "Officiis neque odio veritatis vel perspiciatis.",
                            Price = 404217.986041923260000m,
                            Quantity = 82,
                            Title = "Barrows - Bashirian"
                        },
                        new
                        {
                            Id = new Guid("c30f7cbb-c21f-4c79-8621-ba8d6e0e7564"),
                            Author = "Ada Wolff",
                            Description = "Consequatur natus et sint.",
                            Price = 38531.3753871328070000m,
                            Quantity = 35,
                            Title = "Wiegand, Emard and Osinski"
                        },
                        new
                        {
                            Id = new Guid("a4356be6-75d8-4ae6-aa76-15f0003898e9"),
                            Author = "Ada Wolff",
                            Description = "Doloremque sed aperiam.",
                            Price = 216395.222447396360000m,
                            Quantity = 98,
                            Title = "Kuphal Group"
                        },
                        new
                        {
                            Id = new Guid("c7b1e24f-00b9-4f36-80e3-6153deb37aae"),
                            Author = "Ada Wolff",
                            Description = "Commodi harum autem nostrum ut aut in.",
                            Price = 390486.87949016780000m,
                            Quantity = 76,
                            Title = "Crona, Mayer and Predovic"
                        },
                        new
                        {
                            Id = new Guid("ef348e8f-692b-4255-8bcc-ea813a7b776c"),
                            Author = "Ada Wolff",
                            Description = "Iure accusamus perferendis dolor porro assumenda enim.",
                            Price = 396954.938815575690000m,
                            Quantity = 58,
                            Title = "Blick LLC"
                        },
                        new
                        {
                            Id = new Guid("e25e9afb-d56f-4f7a-a811-ae42bb6868c9"),
                            Author = "Ada Wolff",
                            Description = "Est aperiam perferendis facere animi et asperiores delectus.",
                            Price = 108380.725888948510000m,
                            Quantity = 50,
                            Title = "Muller, Cremin and Mohr"
                        },
                        new
                        {
                            Id = new Guid("54df3fa3-8487-4ead-b792-481cc0b9ef5b"),
                            Author = "Ada Wolff",
                            Description = "Repellendus ut iusto totam.",
                            Price = 160314.457589416260000m,
                            Quantity = 21,
                            Title = "Parisian, Hegmann and Hahn"
                        },
                        new
                        {
                            Id = new Guid("728f67c6-db9d-4e3f-a788-17e76ceab0e6"),
                            Author = "Ada Wolff",
                            Description = "Et similique ut sunt.",
                            Price = 482581.427422184640000m,
                            Quantity = 6,
                            Title = "Dickens and Sons"
                        },
                        new
                        {
                            Id = new Guid("2246365c-45ff-4ffe-a164-2591f5db95e7"),
                            Author = "Ada Wolff",
                            Description = "Molestiae enim et neque dolores quia quidem a.",
                            Price = 17324.5099656659280000m,
                            Quantity = 97,
                            Title = "Wyman - Murray"
                        },
                        new
                        {
                            Id = new Guid("7b1bc506-b809-461a-9d37-af77402f019f"),
                            Author = "Ada Wolff",
                            Description = "Ut deleniti tempora officiis est molestiae.",
                            Price = 169601.50703325640000m,
                            Quantity = 73,
                            Title = "Wilderman Group"
                        },
                        new
                        {
                            Id = new Guid("23924fd3-0cb9-4138-b60f-cd51838248fe"),
                            Author = "Ada Wolff",
                            Description = "Iure provident dolores ullam modi qui sapiente.",
                            Price = 96355.11786745130000m,
                            Quantity = 40,
                            Title = "Howe LLC"
                        },
                        new
                        {
                            Id = new Guid("e47a4328-f4af-485a-a839-3c5ec6206e94"),
                            Author = "Ada Wolff",
                            Description = "Nulla nulla sunt possimus officiis aut et veniam non.",
                            Price = 414534.646772227440000m,
                            Quantity = 92,
                            Title = "Lesch LLC"
                        },
                        new
                        {
                            Id = new Guid("3de53ad0-490a-4a8d-b55c-2d6a54cb4669"),
                            Author = "Ada Wolff",
                            Description = "Distinctio asperiores voluptate id ea.",
                            Price = 454632.964585842060000m,
                            Quantity = 8,
                            Title = "Heidenreich - Yundt"
                        },
                        new
                        {
                            Id = new Guid("f3db1fb7-e535-40ba-851e-b670b290fd1b"),
                            Author = "Ada Wolff",
                            Description = "Nulla accusantium quaerat eos suscipit sit ea nam aliquid nihil.",
                            Price = 32111.2468335607590000m,
                            Quantity = 70,
                            Title = "Parker, Littel and Beier"
                        },
                        new
                        {
                            Id = new Guid("41a8f881-6ab6-4d8f-bf4a-dfe287cfe506"),
                            Author = "Ada Wolff",
                            Description = "Quod id cumque sunt veritatis iure dolores.",
                            Price = 291906.559471130440000m,
                            Quantity = 20,
                            Title = "Dibbert, Ratke and Breitenberg"
                        },
                        new
                        {
                            Id = new Guid("e6ef2c8b-237f-403a-8855-9568d4973d69"),
                            Author = "Ada Wolff",
                            Description = "Quibusdam enim aperiam ut rerum amet.",
                            Price = 495444.020613707330000m,
                            Quantity = 36,
                            Title = "Hansen Inc"
                        },
                        new
                        {
                            Id = new Guid("89931651-84e9-49fa-95ae-ce6da173bf08"),
                            Author = "Ada Wolff",
                            Description = "Nemo maxime rerum aperiam doloremque.",
                            Price = 138441.796654452190000m,
                            Quantity = 98,
                            Title = "Schneider - Cremin"
                        },
                        new
                        {
                            Id = new Guid("6f269221-0266-4a5d-abdf-042e8e1f59b8"),
                            Author = "Ada Wolff",
                            Description = "Qui natus est consequatur quaerat molestiae sunt non est ab.",
                            Price = 278685.57211301050000m,
                            Quantity = 1,
                            Title = "Lakin, Waelchi and Waelchi"
                        },
                        new
                        {
                            Id = new Guid("5b771cb5-f827-49a2-8a15-c88740d3c6ce"),
                            Author = "Ada Wolff",
                            Description = "Nesciunt sint ea magnam nisi.",
                            Price = 480108.805522909910000m,
                            Quantity = 7,
                            Title = "Wiza - Hermiston"
                        },
                        new
                        {
                            Id = new Guid("17a3000a-56dc-4978-8b2d-680c64a7a71b"),
                            Author = "Ada Wolff",
                            Description = "At expedita optio veniam labore aut voluptatem et et.",
                            Price = 214116.124246382810000m,
                            Quantity = 65,
                            Title = "Pagac, Wiza and Wisozk"
                        },
                        new
                        {
                            Id = new Guid("15304f31-e7d4-4320-9be9-67c30172731b"),
                            Author = "Ada Wolff",
                            Description = "Id eos aut.",
                            Price = 316202.149274137760000m,
                            Quantity = 29,
                            Title = "Kihn Inc"
                        },
                        new
                        {
                            Id = new Guid("05643bc1-d4c8-41dc-86de-cc883163244d"),
                            Author = "Ada Wolff",
                            Description = "Quaerat quia itaque dolores iste aut.",
                            Price = 313926.253576961540000m,
                            Quantity = 85,
                            Title = "Kovacek Group"
                        },
                        new
                        {
                            Id = new Guid("99187feb-1c17-48a9-8219-c63dffa0d48f"),
                            Author = "Ada Wolff",
                            Description = "Laboriosam eum eligendi tempore eum id recusandae.",
                            Price = 324835.320882912970000m,
                            Quantity = 9,
                            Title = "Considine LLC"
                        },
                        new
                        {
                            Id = new Guid("f72bef9d-6720-4895-8e93-195c659a397e"),
                            Author = "Ada Wolff",
                            Description = "Consequatur sint dolorum quae ex perspiciatis consequatur expedita veniam.",
                            Price = 367495.902439792760000m,
                            Quantity = 68,
                            Title = "Hilpert Group"
                        },
                        new
                        {
                            Id = new Guid("442baf5f-8de7-43a3-9157-9f382122128e"),
                            Author = "Ada Wolff",
                            Description = "Facere et odio eius inventore.",
                            Price = 269572.392812313140000m,
                            Quantity = 18,
                            Title = "Heller - Mohr"
                        },
                        new
                        {
                            Id = new Guid("9f21fe4c-33b1-4e9f-8186-14ab8a16c82b"),
                            Author = "Ada Wolff",
                            Description = "Harum quia in.",
                            Price = 69832.052212795940000m,
                            Quantity = 6,
                            Title = "Beatty - Rau"
                        },
                        new
                        {
                            Id = new Guid("1fcbb275-ae19-42d9-b0ca-0a11d0915ce9"),
                            Author = "Ada Wolff",
                            Description = "Ex quo dolore harum dolorem.",
                            Price = 177251.056328621090000m,
                            Quantity = 38,
                            Title = "Lowe, Block and Runte"
                        },
                        new
                        {
                            Id = new Guid("22368f3c-852f-45d4-bbbc-f598f6323dfd"),
                            Author = "Ada Wolff",
                            Description = "Molestiae enim expedita consequatur ipsum quaerat.",
                            Price = 448621.092023483390000m,
                            Quantity = 54,
                            Title = "Dickinson - Kovacek"
                        },
                        new
                        {
                            Id = new Guid("c4c3b5e1-537a-4811-b777-6dc62eab3f38"),
                            Author = "Ada Wolff",
                            Description = "Facere voluptas ut quaerat et.",
                            Price = 249047.085268376420000m,
                            Quantity = 97,
                            Title = "Lesch, Hickle and Beier"
                        },
                        new
                        {
                            Id = new Guid("298ff798-b18b-4d2f-8a68-be69463b9810"),
                            Author = "Ada Wolff",
                            Description = "Nulla dicta ad hic aut et accusantium aut.",
                            Price = 23042.1735633171150000m,
                            Quantity = 49,
                            Title = "Klein Group"
                        },
                        new
                        {
                            Id = new Guid("c57b2738-32dc-4a69-819d-adaa1c90843c"),
                            Author = "Ada Wolff",
                            Description = "Possimus laudantium possimus optio in quis vitae totam et provident.",
                            Price = 364948.677320956460000m,
                            Quantity = 79,
                            Title = "Swaniawski LLC"
                        },
                        new
                        {
                            Id = new Guid("0bedccf1-83d5-43cc-9e0f-dc38c92ec598"),
                            Author = "Ada Wolff",
                            Description = "Perferendis a impedit suscipit rerum eum adipisci sunt est.",
                            Price = 361567.809807392640000m,
                            Quantity = 21,
                            Title = "Nader and Sons"
                        },
                        new
                        {
                            Id = new Guid("0ba88379-5978-4781-b606-29c8e9b82f66"),
                            Author = "Ada Wolff",
                            Description = "Fugit et enim iusto unde.",
                            Price = 150412.06732063630000m,
                            Quantity = 75,
                            Title = "Hayes and Sons"
                        },
                        new
                        {
                            Id = new Guid("f54633e6-99c9-4176-ac9b-bb861c429f95"),
                            Author = "Ada Wolff",
                            Description = "Nihil consequatur quia soluta est quas enim tenetur vel.",
                            Price = 93574.713479738810000m,
                            Quantity = 84,
                            Title = "Hackett - Corkery"
                        },
                        new
                        {
                            Id = new Guid("a23b81df-d3d4-417f-8cc3-dcf33da815e5"),
                            Author = "Ada Wolff",
                            Description = "Quibusdam voluptatem praesentium quia quia et repudiandae rerum nisi eum.",
                            Price = 454655.057894430320000m,
                            Quantity = 38,
                            Title = "Crona - Skiles"
                        },
                        new
                        {
                            Id = new Guid("ab6791c4-091d-4ae5-8280-0c05268ae627"),
                            Author = "Ada Wolff",
                            Description = "Culpa voluptatem reiciendis libero nisi rerum rerum molestiae inventore nostrum.",
                            Price = 279088.93361599760000m,
                            Quantity = 75,
                            Title = "Bins, Trantow and Ziemann"
                        },
                        new
                        {
                            Id = new Guid("16ad399d-01c9-488d-9f19-b4ea77d02ee0"),
                            Author = "Ada Wolff",
                            Description = "Quasi et exercitationem temporibus est dolore aliquid ipsam deleniti voluptatem.",
                            Price = 491263.875154548080000m,
                            Quantity = 9,
                            Title = "Rutherford - Kuhn"
                        },
                        new
                        {
                            Id = new Guid("e12d8e28-7740-44c5-9d01-21169a09b119"),
                            Author = "Ada Wolff",
                            Description = "Placeat laudantium rerum ullam.",
                            Price = 326527.408753681580000m,
                            Quantity = 51,
                            Title = "Lubowitz LLC"
                        },
                        new
                        {
                            Id = new Guid("3ba79888-9359-43dc-a35d-58189cd59798"),
                            Author = "Ada Wolff",
                            Description = "Omnis similique dolorem pariatur doloribus.",
                            Price = 420321.034741900940000m,
                            Quantity = 82,
                            Title = "Daniel - Tillman"
                        },
                        new
                        {
                            Id = new Guid("d3299196-e82f-4783-8052-6d1824741696"),
                            Author = "Ada Wolff",
                            Description = "Odit laudantium aspernatur quibusdam et dolorum voluptates dolores amet.",
                            Price = 355193.111892211660000m,
                            Quantity = 82,
                            Title = "Dooley - Rempel"
                        },
                        new
                        {
                            Id = new Guid("fd65ec81-f416-47b3-8d2f-b31cea898b86"),
                            Author = "Ada Wolff",
                            Description = "Eos illum est natus ullam ut saepe beatae aspernatur.",
                            Price = 441222.055004274940000m,
                            Quantity = 69,
                            Title = "Wiza - Jacobson"
                        },
                        new
                        {
                            Id = new Guid("bce4d60a-6c1d-4a63-997a-369662da3d32"),
                            Author = "Ada Wolff",
                            Description = "Tempora nostrum totam architecto corporis.",
                            Price = 224539.574449453750000m,
                            Quantity = 3,
                            Title = "Murazik and Sons"
                        },
                        new
                        {
                            Id = new Guid("f1a2e327-84c0-4dc0-9e8d-811d91a06dc6"),
                            Author = "Ada Wolff",
                            Description = "Nulla ipsa placeat est incidunt libero esse sunt.",
                            Price = 28476.3776278421480000m,
                            Quantity = 59,
                            Title = "Bernier, Hauck and Stracke"
                        },
                        new
                        {
                            Id = new Guid("186d9987-6c2d-4e06-9ced-b1857c5879ca"),
                            Author = "Ada Wolff",
                            Description = "Sed voluptatem quos facilis veniam non voluptas eum.",
                            Price = 109748.115463217060000m,
                            Quantity = 17,
                            Title = "Oberbrunner - Kuhlman"
                        },
                        new
                        {
                            Id = new Guid("3121c1d9-d706-4cfb-a0fc-cb51ed8221a1"),
                            Author = "Ada Wolff",
                            Description = "Modi velit voluptates iusto quidem autem laborum nemo cum.",
                            Price = 274694.12509057910000m,
                            Quantity = 29,
                            Title = "Bode, Runte and Frami"
                        },
                        new
                        {
                            Id = new Guid("7f3343f9-70ef-4efd-8f3b-22f78fdec133"),
                            Author = "Ada Wolff",
                            Description = "Repudiandae incidunt est praesentium reiciendis autem mollitia rem eum.",
                            Price = 395511.066957433340000m,
                            Quantity = 52,
                            Title = "Jacobson - Ritchie"
                        },
                        new
                        {
                            Id = new Guid("a600982e-dda0-48c8-ad46-f76307ed1a0a"),
                            Author = "Ada Wolff",
                            Description = "Minima doloremque voluptas nam praesentium in beatae ab voluptatem.",
                            Price = 142674.948666946840000m,
                            Quantity = 47,
                            Title = "Howell, Raynor and King"
                        },
                        new
                        {
                            Id = new Guid("ba7f576a-6d2d-4b38-b0a7-82d47f65d97e"),
                            Author = "Ada Wolff",
                            Description = "Eos rerum quas reprehenderit.",
                            Price = 425425.517337855780000m,
                            Quantity = 75,
                            Title = "Stroman, Tremblay and Hane"
                        },
                        new
                        {
                            Id = new Guid("e08729b9-b7cb-4829-8aa1-a3d5b0b5101b"),
                            Author = "Ada Wolff",
                            Description = "Et rem ut quod ad.",
                            Price = 433937.269408614920000m,
                            Quantity = 22,
                            Title = "Mohr, Walter and O'Connell"
                        },
                        new
                        {
                            Id = new Guid("a4146eb7-ba21-4cb3-bb66-00db2136cce9"),
                            Author = "Ada Wolff",
                            Description = "Veritatis architecto ducimus excepturi molestias.",
                            Price = 180214.333148968640000m,
                            Quantity = 21,
                            Title = "Zulauf - Bogisich"
                        },
                        new
                        {
                            Id = new Guid("648d6519-50a3-486d-b622-91c091fff7c7"),
                            Author = "Ada Wolff",
                            Description = "Soluta esse nulla eum nostrum eum ipsam.",
                            Price = 305202.072864367690000m,
                            Quantity = 61,
                            Title = "Lind - Emard"
                        },
                        new
                        {
                            Id = new Guid("2fcb66dd-cf23-46ba-aeef-783682d40569"),
                            Author = "Ada Wolff",
                            Description = "Quod ut in.",
                            Price = 294611.674540320960000m,
                            Quantity = 28,
                            Title = "Aufderhar and Sons"
                        },
                        new
                        {
                            Id = new Guid("5d02b338-6b26-4d1c-9979-6e7d3273d180"),
                            Author = "Ada Wolff",
                            Description = "Quo eveniet dolorem at autem dolorem natus nam similique quod.",
                            Price = 294902.919568130710000m,
                            Quantity = 78,
                            Title = "Ledner LLC"
                        },
                        new
                        {
                            Id = new Guid("534f1562-cc4d-463c-bed8-68971c2dbf52"),
                            Author = "Ada Wolff",
                            Description = "Ullam voluptas officia sed magni sunt.",
                            Price = 458515.326451720220000m,
                            Quantity = 2,
                            Title = "Huels Group"
                        },
                        new
                        {
                            Id = new Guid("e4953520-54c4-4939-a39c-ee80b1d79eea"),
                            Author = "Ada Wolff",
                            Description = "Ut a suscipit eos labore omnis delectus magni.",
                            Price = 27769.1696938423850000m,
                            Quantity = 68,
                            Title = "Denesik - Buckridge"
                        },
                        new
                        {
                            Id = new Guid("04294032-fc37-4496-9765-7f0506af3ba3"),
                            Author = "Ada Wolff",
                            Description = "Quas vel placeat consequatur eveniet sed.",
                            Price = 277961.158573621940000m,
                            Quantity = 47,
                            Title = "Walker - Jenkins"
                        },
                        new
                        {
                            Id = new Guid("d6730603-d876-4e61-99d8-63a7a54d4f61"),
                            Author = "Ada Wolff",
                            Description = "Repudiandae est ut itaque atque corporis nulla quia quisquam.",
                            Price = 63524.470304850090000m,
                            Quantity = 2,
                            Title = "McClure - Mann"
                        },
                        new
                        {
                            Id = new Guid("13c872a3-ce46-45b6-890e-941e494bd63a"),
                            Author = "Ada Wolff",
                            Description = "Facilis culpa ad voluptates aut dolores recusandae repellat.",
                            Price = 52513.1593811928850000m,
                            Quantity = 46,
                            Title = "Spencer, Russel and Johnston"
                        },
                        new
                        {
                            Id = new Guid("2ec53d41-d2f5-4d2e-ba68-dbcb171a6369"),
                            Author = "Ada Wolff",
                            Description = "Est voluptas eum quibusdam sed eum mollitia odio voluptatibus.",
                            Price = 63696.433894266590000m,
                            Quantity = 15,
                            Title = "Franecki - Collier"
                        },
                        new
                        {
                            Id = new Guid("d0337f64-6b5f-4441-85a3-8b66d7af6081"),
                            Author = "Ada Wolff",
                            Description = "Reprehenderit quos earum explicabo qui quisquam ab.",
                            Price = 201782.840563912010000m,
                            Quantity = 97,
                            Title = "Goldner, Kihn and Lesch"
                        },
                        new
                        {
                            Id = new Guid("5ff6d6fe-6560-411c-9e67-667f97cdfed1"),
                            Author = "Ada Wolff",
                            Description = "Dolorem dolore et qui quibusdam quaerat quae.",
                            Price = 234142.982844102350000m,
                            Quantity = 37,
                            Title = "Shanahan and Sons"
                        },
                        new
                        {
                            Id = new Guid("f6656669-f9ad-4fc2-9787-3f98f63331a0"),
                            Author = "Ada Wolff",
                            Description = "Minima veritatis quo sit et aut officiis.",
                            Price = 438697.11145872520000m,
                            Quantity = 90,
                            Title = "Champlin - Grimes"
                        },
                        new
                        {
                            Id = new Guid("413be594-9727-44b5-8b54-4066cab6f64f"),
                            Author = "Ada Wolff",
                            Description = "Sit occaecati odio saepe dignissimos qui.",
                            Price = 49907.2725390503920000m,
                            Quantity = 64,
                            Title = "Abbott Inc"
                        },
                        new
                        {
                            Id = new Guid("5b608510-fce5-4898-a671-8fcb29a9fa23"),
                            Author = "Ada Wolff",
                            Description = "Et impedit saepe at voluptatibus iusto et ipsa veritatis beatae.",
                            Price = 255634.008604724180000m,
                            Quantity = 18,
                            Title = "Schaefer - Stracke"
                        },
                        new
                        {
                            Id = new Guid("9444eb2b-2521-4848-9204-8a8c02257f0d"),
                            Author = "Ada Wolff",
                            Description = "Aut eligendi occaecati quod possimus.",
                            Price = 148715.182450982620000m,
                            Quantity = 78,
                            Title = "Gislason, Nikolaus and Crooks"
                        },
                        new
                        {
                            Id = new Guid("81be8f21-3c6f-43dd-a347-84ba8414d00f"),
                            Author = "Ada Wolff",
                            Description = "Labore expedita vel sunt aliquam qui sunt.",
                            Price = 17003.0384679475570000m,
                            Quantity = 86,
                            Title = "Boehm - Maggio"
                        },
                        new
                        {
                            Id = new Guid("aee58f74-cad1-4519-8118-a67643614a64"),
                            Author = "Ada Wolff",
                            Description = "Autem sit praesentium et.",
                            Price = 108069.701596165110000m,
                            Quantity = 19,
                            Title = "Langworth - Larkin"
                        },
                        new
                        {
                            Id = new Guid("ea39d689-927b-4b9c-9cbf-8326e858cb78"),
                            Author = "Ada Wolff",
                            Description = "Ducimus rem exercitationem eaque.",
                            Price = 252560.942256966340000m,
                            Quantity = 54,
                            Title = "Lubowitz, Roberts and Streich"
                        },
                        new
                        {
                            Id = new Guid("1e4eae44-c9f9-4d81-b91d-0eb12d38f633"),
                            Author = "Ada Wolff",
                            Description = "Veritatis voluptas voluptatem.",
                            Price = 118186.81043001650000m,
                            Quantity = 65,
                            Title = "Hyatt, Walsh and Ortiz"
                        },
                        new
                        {
                            Id = new Guid("2399fc82-8614-4406-812c-b1c740e64689"),
                            Author = "Ada Wolff",
                            Description = "Eum error soluta dolores.",
                            Price = 362760.076639698630000m,
                            Quantity = 57,
                            Title = "Conn - Stehr"
                        },
                        new
                        {
                            Id = new Guid("f815306f-c714-4a2a-9401-95f5530a02fd"),
                            Author = "Ada Wolff",
                            Description = "Reiciendis autem cum doloremque aut inventore.",
                            Price = 170654.753207806130000m,
                            Quantity = 18,
                            Title = "Carter Inc"
                        },
                        new
                        {
                            Id = new Guid("3e5e7495-98fd-4cee-94c0-6661114ffcf0"),
                            Author = "Ada Wolff",
                            Description = "Odit perspiciatis ut.",
                            Price = 97810.202858201180000m,
                            Quantity = 4,
                            Title = "Gutmann - Huel"
                        },
                        new
                        {
                            Id = new Guid("3ddeac80-9a58-4947-ab61-4a831f16ec90"),
                            Author = "Ada Wolff",
                            Description = "Voluptatem qui distinctio excepturi similique vero cum perferendis ut.",
                            Price = 81387.835514627170000m,
                            Quantity = 20,
                            Title = "Walsh and Sons"
                        },
                        new
                        {
                            Id = new Guid("3d1f7507-0636-4e79-a0df-e302db44d726"),
                            Author = "Ada Wolff",
                            Description = "Necessitatibus rem minus reprehenderit voluptas porro sunt in.",
                            Price = 489809.877154731760000m,
                            Quantity = 7,
                            Title = "Adams, Franecki and Howell"
                        },
                        new
                        {
                            Id = new Guid("fe0d0c51-b7f4-4c3e-82b4-058c9f75339f"),
                            Author = "Ada Wolff",
                            Description = "Error illum sunt voluptas at facilis reiciendis.",
                            Price = 293702.212661006090000m,
                            Quantity = 22,
                            Title = "Kerluke and Sons"
                        },
                        new
                        {
                            Id = new Guid("6a11803f-f576-4aa2-9a40-3bf0e1cfdd51"),
                            Author = "Ada Wolff",
                            Description = "Aliquam eaque quam.",
                            Price = 190021.227223901350000m,
                            Quantity = 92,
                            Title = "Kub - Effertz"
                        },
                        new
                        {
                            Id = new Guid("6908533d-2930-4615-b0fa-156b37fa4fa4"),
                            Author = "Ada Wolff",
                            Description = "Architecto dolores repudiandae animi quia ut et totam dolorum.",
                            Price = 163519.65010055520000m,
                            Quantity = 55,
                            Title = "Robel, Rolfson and Pfannerstill"
                        },
                        new
                        {
                            Id = new Guid("f040af7b-5773-4bcc-9805-fe168eb61d21"),
                            Author = "Ada Wolff",
                            Description = "Repellat voluptate eveniet doloribus voluptatum consequuntur vel molestias sapiente.",
                            Price = 304117.416945773050000m,
                            Quantity = 24,
                            Title = "Bernhard - Schaden"
                        });
                });

            modelBuilder.Entity("BookStore.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.ComplexProperty<Dictionary<string, object>>("ShippingAddress", "BookStore.Domain.Orders.Order.ShippingAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("shipping_address_address_line");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("shipping_address_city");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("shipping_address_district");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("shipping_address_town");
                        });

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", "books");
                });

            modelBuilder.Entity("BookStore.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", "books");
                });

            modelBuilder.Entity("BookStore.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "books");
                });

            modelBuilder.Entity("BookStore.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("handler_name");

                    b.HasKey("OutboxMessageId", "HandlerName")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "books");
                });

            modelBuilder.Entity("BookStore.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("BookStore.Domain.Orders.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_order_items_orders_order_id");
                });

            modelBuilder.Entity("BookStore.Domain.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
